### PR TITLE
Add a new target to run phpcs with phing.

### PR DESCRIPTION
**Pull request by drupol**
Hi,

This is a small pull request that adds a new target: "phpcs"

When runned (**./bin/phing phpcs**), it will output the result of the phpcs command in the terminal but also in a file in the directory **reports**.

This way we can control how the phpcs command is runned and thus, help newcomers to verify the code without looking for the right syntax.

I'll probably improve the exec call next week and use the phpcodesniffer tag instead.

In the meantime, let me know what you think.

### CODE REVIEW

**Comment by verbruggenalex** [comment]
I think it's a good idea. This will align more the way people execute phpcs and we will get the same results as the developers. Now we still encounter people that don't know how to run the phpcs properly. This is probably because there was no accurate documentation.

The only thing I'm not sure about is if we are actually going to need this when the automated qa target "mjolnir" will get used to do pretty much the same and more. If you're interested Pol you can test the fpfis-reference repository where we are working on the QA automation: https://github.com/ec-europa/fpfis-reference/blob/master/build.test.xml#L153 It's running the FPFISQualityAssurance class: https://github.com/ec-europa/qa-automation/blob/master/QualityAssuranceTask.php

Once that is finished the phpcs target will become obsolete I think.

**Comment by mathiasselleslach** [comment]
I agree with @verbruggenalex .
IMHO we should focus on making sure that the "mjolnir" target can be used as an "all-in-one" package for both contractors and QA team members. So that both audiences can have the same results for *all checks*, including phpcs that is.

**Comment by drupol** [comment]
As I'm not aware yet of "What's coming soon", I proposed this to help people "in the meantime".

I will check the fpfis-reference repo today and see the QA automation tool as advised by @verbruggenalex .

I will give some feedback asap.

**Comment by tatarbj** [comment]
@verbruggenalex is it already solved functionally or should we discussed still this proposal to have a dedicated phing target for making the report storable? mjolnir can be piped to a file, so i think that covers this need, but surely it should be discussed.

**Comment by verbruggenalex** [comment]
Closing because of new qa-automation tools that provide a dedicated phpcs command.

**Pull request closed without merging**
